version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: parallax_postgres_db
    restart: always     # Always restart the container if it stops
    environment:
      # Database credentials
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"     # Map DATABASE_PORT of the container to port DATABASE_PORT on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
  web:
    build: .        # Build the Dockerfile in the current directory
    container_name: parallax_web_app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${APP_SECRET_KEY}
    volumes:
      - .:/usr/src/app  # Mount current directory to /usr/src/app in the container
    ports:
      - "5000:5000"   # Map port 5000 of the container to port 5000 on the host
    depends_on:
      - db
    # Gunicorn is run from CMD from Dockerfile

# Volume for persistent database storage even if the container is removed/closed
volumes:
  postgres_data:
